# Generated by Django 2.0 on 2019-01-13 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infilect_app', '0002_group_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='owner_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
