# Generated by Django 2.0 on 2019-01-13 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infilect_app', '0003_photo_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='infilect_app.Group'),
        ),
    ]
