# Generated by Django 2.0 on 2019-01-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infilect_app', '0005_auto_20190113_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='asd', max_length=252),
            preserve_default=False,
        ),
    ]
